version: "3"

silent: true

vars:
  YEARS: 6
  DB: bigquery

tasks:
  venv:
    cmds:
      - python3 -m venv .venv

  install:
    cmds:
      - source .venv/bin/activate && pip install --upgrade pip -q
      - source .venv/bin/activate && pip install -r requirements.txt -q
      - source .venv/bin/activate && pip install dbt-core dbt-{{.DB}} -q

  gen:
    cmds:
      - source .venv/bin/activate && jafgen {{.YEARS}}

  seed:
    cmds:
      - source .venv/bin/activate && dbt seed

  clean:
    cmds:
      - rm -rf jaffle-data
      - source .venv/bin/activate && pip uninstall dbt-core dbt-{{.DB}} -y -q

  load:
    deps: [venv, install, gen, seed, clean]
    cmds:
      - echo "Data loading process completed"